# Generated by Django 3.1 on 2023-03-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20230309_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catogery_name',
            new_name='category_name',
        ),
    ]
